version: '3.8'

volumes:
  zookeeper-data:
  zookeeper-logs:
  kafka-data-1:
  kafka-data-2:
  kafka-data-3:

networks:
  default:
    driver: bridge

services:
  zookeeper:
    image: debezium/zookeeper:latest
    container_name: micro_service_zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/logs
  
  kafka:
    image: debezium/kafka:latest
    container_name: micro_service_kafka
    ports:
      - 9092:9092
    environment:
      - BROKER_ID=1
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS:'PLAINTEXT://localhost:9092'
    links:
      - zookeeper
    volumes:
      - kafka-data-1:/kafka

  akhq:
    image: tchiotludo/akhq
    container_name: micro_service_akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka-1:9092"
    ports:
      - 8030:8080