name: DEPLOY_AUTHENTICATION

on:
  push:
    branches:
      - main
      - master

defaults:
  run:
    working-directory: ./authentication.api

jobs:

  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false
          ref: master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "brodalee/ms:auth-phpfpm"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker/nginx
          push: true
          tags: "brodalee/ms:auth-nginx"